# Generated by Django 4.2.17 on 2025-05-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.IntegerField(max_length=10)),
                ('Name', models.CharField(max_length=100)),
                ('Platform', models.CharField(max_length=50)),
                ('Year', models.DateField()),
                ('Genre', models.CharField(max_length=100)),
                ('Publisher', models.CharField(max_length=100)),
                ('NA_Sales', models.FloatField(max_length=100)),
                ('EU_Sales', models.FloatField(max_length=100)),
                ('JP_Sales', models.FloatField(max_length=100)),
                ('Other_Sales', models.FloatField(max_length=100)),
                ('Global_Sales', models.FloatField(max_length=100)),
            ],
        ),
    ]
