# Generated by Django 4.2.17 on 2025-06-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='Rank',
        ),
    ]
