# Generated by Django 5.2.2 on 2025-06-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0003_juego_rank_alter_juego_eu_sales_alter_juego_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='API_ID',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='Image_URL',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
