# Generated by Django 4.2.17 on 2025-06-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0004_juego_api_id_juego_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='Year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
