# Generated by Django 4.2.17 on 2026-06-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0005_alter_juego_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='Summary_ES',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='EU_Sales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='Global_Sales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='JP_Sales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='NA_Sales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='Other_Sales',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
