# Generated by Django 4.2.17 on 2026-06-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0006_summary_es'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='Genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='Platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='Publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
