"""
Django settings for tp3_crud project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv


load_dotenv()

TWITCH_CLIENT_ID = os.getenv('ryibth8v88mg80rr07x098mvv3i696')
TWITCH_CLIENT_SECRET = os.getenv('0tt88o4ww4cf0htqfj8vnqi3fiv1d1')
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kcidmmnj3b!@t!^tu)3oau+-ef=8ht2rt3h8&2%tqxbe*$(kmu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

LOGOUT_REDIRECT_URL = '/home/'
# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_bootstrap5'

]

LOCAL_APPS = [
    'apps.juego',
    'django_python3_ldap',
]

INSTALLED_APPS = DJANGO_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tp3_crud.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tp3_crud.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de autenticación LDAP para Active Directory
AUTHENTICATION_BACKENDS = [
    'django_python3_ldap.auth.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',  # Fallback a autenticación local
]

# Configuración del servidor LDAP/AD
LDAP_AUTH_URL = os.getenv('LDAP_AUTH_URL', 'ldap://tu-servidor-ad.dominio.local:389')

# Si usas SSL/TLS (recomendado), usa ldaps:// y puerto 636
# LDAP_AUTH_URL = os.getenv('LDAP_AUTH_URL', 'ldaps://tu-servidor-ad.dominio.local:636')

# Usar conexión TLS para seguridad
LDAP_AUTH_USE_TLS = False  # Cambiar a True si el servidor lo soporta

# Usuario de búsqueda (bind user) - necesario para buscar usuarios en AD
LDAP_AUTH_CONNECTION_USERNAME = os.getenv('LDAP_AUTH_CONNECTION_USERNAME', 'CN=bind_user,CN=Users,DC=dominio,DC=local')
LDAP_AUTH_CONNECTION_PASSWORD = os.getenv('LDAP_AUTH_CONNECTION_PASSWORD', 'password_del_bind_user')

# Base DN donde buscar usuarios
LDAP_AUTH_SEARCH_BASE = os.getenv('LDAP_AUTH_SEARCH_BASE', 'CN=Users,DC=dominio,DC=local')

# Filtro para buscar usuarios - Para AD usa sAMAccountName
LDAP_AUTH_USER_LOOKUP_FIELDS = ('username',)
LDAP_AUTH_USER_FIELDS = {
    'username': 'sAMAccountName',
    'first_name': 'givenName',
    'last_name': 'sn',
    'email': 'mail',
}

# Formato del DN del usuario
LDAP_AUTH_OBJECT_CLASS = 'user'

# Sincronización de usuarios
LDAP_AUTH_SYNC_USER_RELATIONS = None

# Formato de búsqueda de usuarios
LDAP_AUTH_FORMAT_SEARCH_FILTERS = 'ldap_sync.active_directory.search_filters'
LDAP_AUTH_FORMAT_USERNAME = 'django_python3_ldap.utils.format_username_active_directory'

# Limpieza del nombre de usuario
LDAP_AUTH_CLEAN_USER_DATA = 'django_python3_ldap.utils.clean_user_data'
